CHUNK_SIZE = 32
TILE_SIZE = 64

WORLD_TICK_RATE = 60
WORLD_TICK_INTERVAL = 1.0  / WORLD_TICK_RATE

NETWORK_TICK_RATE = 20
NETWORK_TICK_INTERVAL = 1.0 / NETWORK_TICK_RATE

PLAYER_SPEED = 5.0
PLAYER_VIEW_DISTANCE = 3